### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by hoksilato** [dungphanx/CoderRestaurant#1]
Hi @dungphanx

Could you please correct your Heroku app link? We got below error when access your link.

```
There is no app configured at that hostname.
Perhaps the app owner has renamed it, or you mistyped the URL.
```

**Comment by dungphanx** [comment]
Dear @hoksilato

Sorry about heroku app, I don't know why It not working. I tried to remove app and create new app at https://warm-garden-13934.herokuapp.com/
However, It's not working also.

>  -----> Ruby app detected
> -----> Compiling Ruby/Rails
> -----> Using Ruby version: ruby-2.3.1
> -----> Installing dependencies using bundler 1.11.2
>        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
>        Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
>        Fetching gem metadata from https://rubygems.org/..........
>        Fetching version metadata from https://rubygems.org/...
>        Fetching dependency metadata from https://rubygems.org/..
>        Installing i18n 0.7.0
>        Installing concurrent-ruby 1.0.2
>        Installing rake 11.2.2
>        Installing minitest 5.9.0
>        Installing builder 3.2.2
>        Installing thread_safe 0.3.5
>        Installing erubis 2.7.0
>        Installing pig-config 1.1.7
>        Installing mini_portile2 2.1.0
>        Installing rack 2.0.1
>        Installing nio4r 1.2.1 with native extensions
>        Installing websocket-extensions 0.1.2
>        Installing are 7.0.0
>        Installing mime-types-data 3.2016.0521
>        Installing execs 2.7.0
>        Installing sass 3.4.22
>        Installing coffee-script-source 1.10.0
>        Installing method_source 0.8.2
>        Installing thor 0.19.1
>        Installing multi_json 1.12.1
>        Installing pg 0.18.4 with native extensions
>        Installing puma 3.4.0 with native extensions
>        Using bundler 1.11.2
>        Installing rails_serve_static_assets 0.0.5
>        Installing rails_stdout_logging 0.0.5
>        Installing tilt 2.0.5
>        Installing turbolinks-source 5.0.0
>        Installing faker 1.6.5
>        Installing tzinfo 1.2.2
>        Installing nokogiri 1.6.8 with native extensions
>        Installing rack-test 0.6.3
>        Installing sprockets 3.6.3
>        Installing websocket-driver 0.6.4 with native extensions
>        Installing mime-types 3.1
>        Installing autoprefixer-rails 6.3.7
>        Installing uglier 3.0.0
>        Installing coffee-script 2.4.1
>        Installing rails_12factor 0.0.3
>        Installing turbolinks 5.0.0
>        Installing active support 5.0.0
>        Installing mail 2.6.4
>        Installing bootstrap 4.0.0.alpha3
>        Installing global 0.3.6
>        Installing activemodel 5.0.0
>        Installing jbuilder 2.5.0
>        Installing active job 5.0.0
>        Installing actierecord 5.0.0
>        Installing rails-dom-testins 2.0.1
>        Installing loofah 2.0.3
>        Installing rails-html-sanitiser 1.0.3
>        Installing actionview 5.0.0
>        Installing actionpack 5.0.0
>        Installing actionmailer 5.0.0
>        Installing actionable 5.0.0
>        Installing railties 5.0.0
>        Installing kaminari 0.17.0
>        Installing sprockets-rails 3.1.1
>        Installing coffee-rails 4.2.1
>        Installing sass-rails 5.0.5
>        Installing query-rails 4.1.1
>        Installing rails 5.0.0
>        Bundle complete! 19 Gemfile dependencies, 61 gems now installed.
>        Gems in the groups development and test were not installed.
>        Bundled gems are installed into ./vendor/bundle.
>        Bundle completed (33.26s)
>        Cleaning up the bundler cache.
>        Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
> -----> Preparing app for Rails asset pipeline
>        Running: rake assets:precompile
>        I, [2016-07-15T18:04:48.634958 #1235]  INFO -- : Writing /tmp/build_b6a5647bf1ee6a011e4ad96e2be87200/public/assets/application-81fc2d93e00013a8bcb81a3b5da1525b2d09206c243db600d33308c727b9e840.js
>        I, [2016-07-15T18:04:48.636005 #1235]  INFO -- : Writing /tmp/build_b6a5647bf1ee6a011e4ad96e2be87200/public/assets/application-81fc2d93e00013a8bcb81a3b5da1525b2d09206c243db600d33308c727b9e840.js.gz
>        I, [2016-07-15T18:04:51.401561 #1235]  INFO -- : Writing /tmp/build_b6a5647bf1ee6a011e4ad96e2be87200/public/assets/application-e6f697565984a15aae65e31ca6e654a68f70558a672bafed785a33ab5bc3fdbe.css
>        I, [2016-07-15T18:04:51.401822 #1235]  INFO -- : Writing /tmp/build_b6a5647bf1ee6a011e4ad96e2be87200/public/assets/application-e6f697565984a15aae65e31ca6e654a68f70558a672bafed785a33ab5bc3fdbe.css.gz
>        Asset precompilation completed (7.88s)
>        Cleaning assets
>        Running: rake assets:clean
> 
> ###### WARNING:
> 
> ```
>    No Procfile detected, using the default web server.
>    We recommend explicitly declaring how to boot your server process via a Profile.
>    https://devcenter.heroku.com/articles/ruby-default-web-server
> ```
> 
> -----> Discovering process types
>        Procfile declares types     -> (none)
>        Default types for buildpack -> console, rake, web, worker
> -----> Compressing...
>        Done: 31.7M
> -----> Launching...
>        Released v5
>        https://warm-garden-13934.herokuapp.com/ deployed to Heroku

It still work fine on my local, but in heroku is not.
One more thing is: when I add gem `gem 'rails-assets-tether'` to Gemfile. I can't deploy app

**Comment by hoksilato** [comment]
Hi @dungphanx 

Actually your app was deployed successfully now, but it's got errors.

```
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```

Check your Heroku logs with command `heroku logs -n 200` and see the errors.

**Comment by dungphanx** [comment]
Dear @hoksilato 

I removed user_mailer file, because I found this line when I check logs

>  2016-07-15T18:27:18.906648+00:00 app[web.1]: /app/app/mailers/user_mailer.rb:1:in `<top > (required)>': superclass must be a Class (Module given) (TypeError)

And I re-pushed heroku again, this logs show as follow and my app still not working?
Could you help me, please. Could you give me Facebook or another app for ease of discussion

> 2016-07-15T18:39:19.090247+00:00 heroku[slug-compiler]: Slug compilation started
> 2016-07-15T18:39:19.090252+00:00 heroku[slug-compiler]: Slug compilation finished
> 2016-07-15T18:39:18.860154+00:00 heroku[api]: Deploy d5b2afd by dungphanx@gmail.com
> 2016-07-15T18:39:18.860260+00:00 heroku[api]: Release v6 created by dungphanx@gmail.com
> 2016-07-15T18:39:19.281384+00:00 heroku[web.1]: State changed from crashed to starting
> 2016-07-15T18:39:21.622532+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 11064 -e production`
> 2016-07-15T18:39:25.188770+00:00 app[web.1]: => Booting Puma
> 2016-07-15T18:39:25.188821+00:00 app[web.1]: => Run `rails server -h` for more startup options
> 2016-07-15T18:39:25.188811+00:00 app[web.1]: => Rails 5.0.0 application starting in production on http://0.0.0.0:11064
> 2016-07-15T18:39:26.333985+00:00 app[web.1]: \* Listening on tcp://0.0.0.0:11064
> 2016-07-15T18:39:26.333805+00:00 app[web.1]: Puma starting in single mode...
> 2016-07-15T18:39:26.333852+00:00 app[web.1]: \* Environment: production
> 2016-07-15T18:39:26.333824+00:00 app[web.1]: \* Version 3.4.0 (ruby 2.3.1-p112), codename: Owl Bowl Brawl
> 2016-07-15T18:39:26.333840+00:00 app[web.1]: \* Min threads: 5, max threads: 5
> 2016-07-15T18:39:26.334200+00:00 app[web.1]: Use Ctrl-C to stop
> 2016-07-15T18:39:26.358583+00:00 heroku[web.1]: State changed from starting to up
> 2016-07-15T18:39:31.053240+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
> 2016-07-15T18:39:31.053201+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9]   
> 2016-07-15T18:39:31.044699+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] Started GET "/app" for 103.199.41.58 at 2016-07-15 18:39:31 +0000
> 2016-07-15T18:39:31.053131+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9]   
> 2016-07-15T18:39:31.053166+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] ActionController::RoutingError (No route matches [GET] "/app"):
> 2016-07-15T18:39:31.053423+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/tagged_logging.rb:70:in`tagged'
> 2016-07-15T18:39:31.053499+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/request_id.rb:24:in `call'
> 2016-07-15T18:39:31.053395+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/tagged_logging.rb:26:in`tagged'
> 2016-07-15T18:39:31.053455+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:24:in `call'
> 2016-07-15T18:39:31.053320+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:36:in`call_app'
> 2016-07-15T18:39:31.053325+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:24:in `block in call'
> 2016-07-15T18:39:31.053282+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in`call'
> 2016-07-15T18:39:31.053367+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/tagged_logging.rb:70:in `block in tagged'
> 2016-07-15T18:39:31.053743+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:522:in`call'
> 2016-07-15T18:39:31.053775+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/configuration.rb:224:in `call'
> 2016-07-15T18:39:31.053570+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in`call'
> 2016-07-15T18:39:31.053672+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/static.rb:136:in `call'
> 2016-07-15T18:39:31.053655+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/executor.rb:12:in`call'
> 2016-07-15T18:39:31.053535+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
> 2016-07-15T18:39:31.053702+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in`call'
> 2016-07-15T18:39:31.053610+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
> 2016-07-15T18:39:31.053832+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/server.rb:569:in`handle_request'
> 2016-07-15T18:39:31.053858+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/server.rb:406:in `process_client'
> 2016-07-15T18:39:31.053993+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in`block in spawn_thread'
> 2016-07-15T18:39:31.053941+00:00 app[web.1]: [033ed607-c957-494d-a665-ba92fdaad7a9] vendor/bundle/ruby/2.3.0/gems/puma-3.4.0/lib/puma/server.rb:271:in `block in run'
> 2016-07-15T18:39:31.055900+00:00 heroku[router]: at=info method=GET path="/app" host=warm-garden-13934.herokuapp.com request_id=033ed607-c957-494d-a665-ba92fdaad7a9 fwd="103.199.41.58" dyno=web.1 connect=0ms service=59ms status=404 bytes=1744

**Comment by hoksilato** [comment]
Hi @dungphanx 

Did you join the tutorial session and find the solution yet?

**Comment by dungphanx** [comment]
Dear @hoksilato 

I'm not joined the tutorial session this morning.

**Comment by hoksilato** [comment]
I saw you found the solution, great job.
